Oddestoodds/ODDESTOODDS.WebUI/Controllers/RolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using ODDESTOODDS.WebUI.Helpers;
using ODDESTOODDS.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace ODDESTOODDS.WebUI.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        // GET: Roles
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);

        }

        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                context.Roles.Add(new IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: /Roles/Edit/5
        public ActionResult Edit(string id)
        {
            var identityRole = context.Roles.Where(r => r.Id.Equals(id, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(identityRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IdentityRole role)
        {
            try
            {
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //GET: /Roles/Delete
        public ActionResult Delete(string id)
        {
            var identityRole = context.Roles.Where(r => r.Id.Equals(id, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(identityRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: /Roles/ManageUserRoles
        public ActionResult ManageUserRoles()
        {
            // prepopulate roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList()
                .Select(rr => new SelectListItem
                {
                    Value = rr.Name.ToString(),
                    Text = rr.Name
                }).ToList();

            var listUser = context.Users.OrderBy(r => r.UserName).ToList()
                .Select(rr => new SelectListItem
                {
                    Value = rr.UserName.ToString(),
                    Text = rr.UserName
                }).ToList();

            ViewBag.Roles = list;
            ViewBag.UserName = listUser;
            return View();
        }

        // POST: /Roles/RoleAddToUser
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRoleToUser(string UserName, string RoleName)
        {
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            var account = new AccountController();
            //account.UserManager.AddToRole(user.Id, RoleName);
            UserManager.AddToRole(user.Id, RoleName);

            ViewBag.ResultMessage = "Role created successfully !";

            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            var listUser = context.Users.OrderBy(r => r.UserName).ToList().Select(rr => new SelectListItem{Value = rr.UserName.ToString(),Text = rr.UserName}).ToList();
            ViewBag.Roles = list;
            ViewBag.UserName = listUser;


            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
               

                ViewBag.RolesForThisUser = UserManager.GetRoles(user.Id);

                // prepopulat roles for the view dropdown
                var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
                var listUser = context.Users.OrderBy(r => r.UserName).ToList().Select(rr => new SelectListItem { Value = rr.UserName.ToString(), Text = rr.UserName }).ToList();

                ViewBag.Roles = list;
                ViewBag.UserName = listUser;

            }

            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string UserName, string RoleName)
        {
            var account = new AccountController();
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            if (UserManager.IsInRole(user.Id, RoleName))
            {
                UserManager.RemoveFromRole(user.Id, RoleName);
                ViewBag.ResultMessage = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.ResultMessage = "This user doesn't belong to selected role.";
            }
            // prepopulat roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            var listUser = context.Users.OrderBy(r => r.UserName).ToList().Select(rr => new SelectListItem { Value = rr.UserName.ToString(), Text = rr.UserName }).ToList();

            ViewBag.Roles = list;
            ViewBag.UserName = listUser;

            return View("ManageUserRoles");
        }
    }
}

Oddestoodds/ODDESTOODDS.WebUI/Views/Roles/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create Role</h2>
@Html.ActionLink("List Roles", "Index") | @Html.ActionLink("Manage User Role", "ManageUserRoles")
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div>
        Role name
    </div>
    <p>
        @Html.TextBox("RoleName")
    </p>
    <input type="submit" value="Save" />
}

Oddestoodds/ODDESTOODDS.WebUI/Views/Roles/Edit.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Role</h2>

@Html.ActionLink("List Roles", "Index") | @Html.ActionLink("Manage User Role", "ManageUserRoles")
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    <div>
        Role name
    </div>
    <p>
        @Html.TextBoxFor(model => model.Name)
    </p>
    <input type="submit" value="Save" />
}

Oddestoodds/ODDESTOODDS.WebUI/Views/Roles/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<h2>Roles Listing </h2>

@Html.ActionLink("Create New Role", "Create") | @Html.ActionLink("Manage User Role", "ManageUserRoles")
<hr />
<div>
    @foreach (var role in Model)
    {
        <p>
            <strong>@role.Name | </strong>
            <span onclick="return confirm('Are you sure to delete?')"><a href="/Roles/Delete/@role.Id" class="delLink" style="color:red;">Delete</a></span> |
            @Html.ActionLink("Edit", "Edit", new { roleId = @role.Id })
        </p>
    }
</div>

Oddestoodds/ODDESTOODDS.WebUI/Views/Roles/ManageUserRoles.cshtml
@{
    /**/

    ViewBag.Title = "ManageUserRoles";
}

<h2>Manage User Roles </h2>

<div>

    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#tab_1" data-toggle="tab">Role Add to User</a>
        </li>
        <li>
            <a href="#tab_2" data-toggle="tab">Get Roles for a User</a>
        </li>
        <li>
            <a href="#tab_3" data-toggle="tab">Delete A User from a Role</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab_1">
            <h2></h2>
            @Html.ActionLink("Create New Role", "Create") | @Html.ActionLink("Manage User Role", "ManageUserRoles")


            @using (Html.BeginForm("AddRoleToUser", "Roles"))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <br />
                <p>

                    Username : @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.UserName, "Select ...", new { @class = "form-control" })
                    <br />
                    <br />
                    Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select ...", new { @class = "form-control" })

                </p>

                <input class="btn btn-primary" type="submit" value="Save" />
            }
        </div>
        <div class="tab-pane fade" id="tab_2">
            <h3></h3>
            @using (Html.BeginForm("GetRoles", "Roles"))
            {
                @Html.AntiForgeryToken()
                <p>
                    Username : @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.UserName, "Select ...", new { @class = "form-control" })
                    <br />
                    <input class="btn btn-primary" type="submit" value="Get Roles for this User" />
                </p>
            }

            @if (ViewBag.RolesForThisUser != null)
            {
                <div>
                    <h4>Roles for this user </h4>
                    <ol>
                        @foreach (string s in ViewBag.RolesForThisUser)
                        {
                            <li>@s</li>
                        }
                    </ol>
                </div>
            }
        </div>
        <div class="tab-pane fade" id="tab_3">
            <h3></h3>

            @using (Html.BeginForm("DeleteRoleForUser", "Roles"))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <p>
                    Username : @Html.DropDownList("UserName", (IEnumerable<SelectListItem>)ViewBag.UserName, "Select ...", new { @class = "form-control" })
                    Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select ...", new { @class = "form-control" })

                </p>

                <input type="submit" class="btn btn-primary" value="Delete this user from Role" />
            }

        </div>
    </div>
</div>